apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: writer
spec:
  steps:
    - name: write
      image: ubuntu
      script: echo bar > $(workspaces.task-ws.path)/foo
  workspaces:
    - name: task-ws
