
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ui-build-service
spec:
  description: |
    The pipeline will do UI deployment in AWS CDN from github UI 
    This pipeline will do the following steps:
      - Using the git-clone catalog Task to clone the UI source Code
      - It will do build the UI code , and create the deployment artifacts that need to be copied to S3
      - Then it will git clone the deployment source code 
      - It will copy the build artifacts into the www folder fo deployment folder.
      - It will then invoke the cloud formation template using aws cli
      - Then it should test the UI availability
  params:
  - name: ui-repo-url
    type: string
    description: The UI git repository URL to clone from.
  - name: deployment-repo-url
    type: string
    description: The deployment git repository URL to clone from.
  workspaces:
  - name: ui-code
    description: |
      This workspace will clone the UI codes and build the code
  - name: deployment-code
    description: |
      This workspace will clone the deployment  codes and invoke the AWS cloudformation script
  tasks:
  - name: fetch-repo
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: ui-code
    params:
    - name: url
      value: $(params.ui-repo-url)
  - name: install-dependencies
    runAfter:
      - fetch-repo
    taskRef:
      name: npm
    workspaces:
    - name: source
      workspace: ui-code
    params:
    - name: PATH_CONTEXT
      value: $(workspaces.output.path)
    - name: ARGS
      value:
        - clean-install
  - name: run-test
    runAfter:
      - install-dependencies
    taskRef:
      name: npm
    workspaces:
      - name: source
        workspace: ui-code
    params:
      - name: PATH_CONTEXT
        value: $(workspaces.source.path)
      - name: ARGS
        value:
          - test
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ui-build-service-run
spec:
  pipelineRef:
    name: ui-build-service
  workspaces:
  - name: ui-code
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: deployment-code
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  params:
  - name: ui-repo-url
    value: https://github.com/AppkubeCloud/appkube-standalone-ui.git
  - name: deployment-repo-url
    value: https://github.com/dcanadillas/petclinic-kaniko.git
