
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-service
spec:
  description: |
    The pipeline will do UI deployment in AWS CDN from github UI 
    This pipeline will do the following steps:
      - Using the git-clone catalog Task to clone the UI source Code
      - It will do build the UI code , and create the deployment artifacts that need to be copied to S3
      - Then it will git clone the deployment source code 
      - It will copy the build artifacts into the www folder fo deployment folder.
      - It will then invoke the cloud formation template using aws cli
      - Then it should test the UI availability
  params:
  - name: ui-repo-url
    type: string
    description: The UI git repository URL to clone from.
  - name: deployment-repo-url
    type: string
    description: The deployment git repository URL to clone from.
  - name: dockerImageUrl
    type: string
    description: Docker Image URL to push the image
  workspaces:
  - name: shared-data
    description: |
      This workspace will receive the cloned git repo and be passed
      to the next Task to list all cloned files and directories.
  - name: dockerconfig-secret
    description: |
      This workspace will have docker config.json
  tasks:
  - name: fetch-repo
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
  - name: build-maven
    runAfter: ["fetch-repo"]
    taskRef:
      name: build-maven
    workspaces:
    - name: source
      workspace: shared-data
    params:
    - name: workingDir
      value: $(workspaces.source.path)
  - name: build-kaniko
    runAfter: ["build-maven"]
    taskRef:
      name: build-kaniko
    workspaces:
    - name: source
      workspace: shared-data
    - name: dockerconfig
      workspace: dockerconfig-secret
    params:
    - name: IMAGE
      value: $(params.dockerImageUrl)
    - name: DOCKERFILE
      value: $(workspaces.source.path)/Dockerfile
    - name: CONTEXT
      value: ./
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-service-run
spec:
  pipelineRef:
    name: build-service
  workspaces:
  - name: dockerconfig-secret
    secret:
      secretName: kaniko-secret
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  params:
  - name: repo-url
    value: https://github.com/dcanadillas/petclinic-kaniko.git
  - name: dockerImageUrl
    value: synectiks/docker-builders:kaniko
